import { Text } from '@blocksuite/notesgraph/store';
import { Service } from '@notesgraph/infra';

import type { DocsService } from '../../doc';
import { getLinkCardBaseUrl } from '../../link-card';

/**
 * Payload of the link-card sidecar's `/clip/transcript` endpoint (a mirror of
 * `VideoTranscript` in `@notesgraph/link-card` — that package is server-side
 * only, its index pulls satori/sharp, so the shape is redeclared here).
 */
export interface VideoTranscriptPayload {
  videoId: string;
  url: string;
  title: string;
  channel: string;
  durationSeconds?: number;
  language: string;
  autoGenerated: boolean;
  segments: { start: number; dur: number; text: string }[];
  text: string;
}

export interface IngestedVideoDoc {
  docId: string;
  title: string;
}

/** Is this URL a YouTube *video* link (watch/short/live/embed/youtu.be)? */
export function isYoutubeVideoUrl(url: string): boolean {
  let u: URL;
  try {
    u = new URL(url);
  } catch {
    return false;
  }
  const host = u.hostname.replace(/^www\.|^m\./, '');
  const isId = (id: string | null | undefined) => !!id && /^[\w-]{11}$/.test(id);
  if (host === 'youtu.be') return isId(u.pathname.slice(1).split('/')[0]);
  if (host === 'youtube.com' || host === 'youtube-nocookie.com') {
    if (u.pathname === '/watch') return isId(u.searchParams.get('v'));
    return /^\/(shorts|embed|live|v)\/[\w-]{11}/.test(u.pathname);
  }
  return false;
}

function formatTimestamp(seconds: number): string {
  const s = Math.floor(seconds);
  const h = Math.floor(s / 3600);
  const m = Math.floor((s % 3600) / 60);
  const sec = s % 60;
  const mm = h > 0 ? String(m).padStart(2, '0') : String(m);
  return `${h > 0 ? `${h}:` : ''}${mm}:${String(sec).padStart(2, '0')}`;
}

function formatDuration(seconds: number | undefined): string | null {
  if (!seconds || !Number.isFinite(seconds)) return null;
  return formatTimestamp(seconds);
}

/**
 * Group caption segments into readable paragraphs of roughly `targetChars`,
 * each prefixed with the start timestamp of its first segment.
 */
export function chunkTranscript(
  segments: VideoTranscriptPayload['segments'],
  targetChars = 500
): string[] {
  const paragraphs: string[] = [];
  let current: string[] = [];
  let currentLen = 0;
  let currentStart = 0;
  const flush = () => {
    if (current.length === 0) return;
    paragraphs.push(`[${formatTimestamp(currentStart)}] ${current.join(' ')}`);
    current = [];
    currentLen = 0;
  };
  for (const segment of segments) {
    if (current.length === 0) currentStart = segment.start;
    current.push(segment.text);
    currentLen += segment.text.length + 1;
    if (currentLen >= targetChars) flush();
  }
  flush();
  return paragraphs;
}

/**
 * Turn a dropped video link into a transcript note: fetches the transcript
 * through the link-card sidecar (YouTube's caption endpoints are not
 * CORS-readable from the browser) and materializes it as a normal doc —
 * video bookmark on top, then timestamped transcript paragraphs. Being a
 * plain doc, it rides the regular search indexer, so the whole transcript is
 * immediately searchable alongside your notes.
 */
export class VideoIngestionService extends Service {
  constructor(private readonly docsService: DocsService) {
    super();
  }

  async fetchTranscript(url: string): Promise<VideoTranscriptPayload> {
    const endpoint = `${getLinkCardBaseUrl()}/clip/transcript?url=${encodeURIComponent(url)}`;
    const res = await fetch(endpoint);
    if (!res.ok) {
      let message = `Transcript fetch failed (${res.status})`;
      try {
        const body = (await res.json()) as { error?: string };
        if (body.error) message = body.error;
      } catch {
        // non-JSON error body — keep the status message
      }
      throw new Error(message);
    }
    return (await res.json()) as VideoTranscriptPayload;
  }

  /**
   * Fetch the transcript for `url` and create the transcript doc.
   * Returns the new doc so callers can link/open it.
   */
  async ingestYoutubeTranscript(url: string): Promise<IngestedVideoDoc> {
    const transcript = await this.fetchTranscript(url);

    const record = this.docsService.createDoc({ title: transcript.title });
    const { doc, release } = this.docsService.open(record.id);
    try {
      const disposePriorityLoad = doc.addPriorityLoad(10);
      await doc.waitForSyncReady();
      disposePriorityLoad();
      const bsDoc = doc.blockSuiteDoc;
      const [note] = bsDoc.getBlocksByFlavour('notesgraph:note');
      if (note) {
        bsDoc.addBlock(
          'notesgraph:bookmark' as never, // TODO(eyhn): fix type
          { url: transcript.url, title: transcript.title },
          note.id
        );
        const duration = formatDuration(transcript.durationSeconds);
        const metaParts = [
          transcript.channel,
          duration,
          `${transcript.language} captions${transcript.autoGenerated ? ' (auto-generated)' : ''}`,
        ].filter(Boolean);
        bsDoc.addBlock(
          'notesgraph:paragraph' as never, // TODO(eyhn): fix type
          { text: new Text(metaParts.join(' · ')) },
          note.id
        );
        bsDoc.addBlock(
          'notesgraph:paragraph' as never, // TODO(eyhn): fix type
          { type: 'h2', text: new Text('Transcript') },
          note.id
        );
        for (const paragraph of chunkTranscript(transcript.segments)) {
          bsDoc.addBlock(
            'notesgraph:paragraph' as never, // TODO(eyhn): fix type
            { text: new Text(paragraph) },
            note.id
          );
        }
      }
    } finally {
      release();
    }
    return { docId: record.id, title: transcript.title };
  }
}
