import { UA } from './constants';

export interface TranscriptSegment {
  /** Start time in seconds. */
  start: number;
  /** Duration in seconds. */
  dur: number;
  text: string;
}

export interface VideoTranscript {
  videoId: string;
  url: string;
  title: string;
  channel: string;
  /** Video length in seconds, when YouTube reports it. */
  durationSeconds?: number;
  /** BCP-47 code of the transcript track, e.g. "en". */
  language: string;
  /** True when the track is auto-generated (ASR) rather than uploaded. */
  autoGenerated: boolean;
  segments: TranscriptSegment[];
  /** The full transcript as plain text. */
  text: string;
}

/** Parse a YouTube video id out of any of the usual URL shapes. */
export function parseYoutubeVideoId(url: string): string | null {
  let u: URL;
  try {
    u = new URL(url);
  } catch {
    return null;
  }
  const host = u.hostname.replace(/^www\.|^m\./, '');
  const idOk = (id: string | null | undefined) =>
    id && /^[\w-]{11}$/.test(id) ? id : null;
  if (host === 'youtu.be') {
    return idOk(u.pathname.slice(1).split('/')[0]);
  }
  if (host === 'youtube.com' || host === 'youtube-nocookie.com') {
    if (u.pathname === '/watch') return idOk(u.searchParams.get('v'));
    const pathMatch = u.pathname.match(/^\/(shorts|embed|live|v)\/([\w-]{11})/);
    if (pathMatch) return idOk(pathMatch[2]);
  }
  return null;
}

interface CaptionTrack {
  baseUrl: string;
  languageCode: string;
  kind?: string; // 'asr' for auto-generated
  name?: { simpleText?: string; runs?: { text: string }[] };
}

interface PlayerResponse {
  videoDetails?: {
    videoId?: string;
    title?: string;
    author?: string;
    lengthSeconds?: string;
  };
  captions?: {
    playerCaptionsTracklistRenderer?: {
      captionTracks?: CaptionTrack[];
    };
  };
  playabilityStatus?: { status?: string; reason?: string };
}

/** Pull the embedded `ytInitialPlayerResponse` JSON out of a watch page. */
function playerResponseFromHtml(html: string): PlayerResponse | null {
  const marker = 'ytInitialPlayerResponse = ';
  const at = html.indexOf(marker);
  if (at < 0) return null;
  const start = at + marker.length;
  // The JSON object ends at the first `};` at brace depth 0 — walk it rather
  // than regexing, titles/descriptions freely contain braces.
  let depth = 0;
  let inString = false;
  let escaped = false;
  for (let i = start; i < html.length; i++) {
    const ch = html[i];
    if (escaped) {
      escaped = false;
    } else if (ch === '\\') {
      escaped = true;
    } else if (ch === '"') {
      inString = !inString;
    } else if (!inString) {
      if (ch === '{') depth++;
      else if (ch === '}') {
        depth--;
        if (depth === 0) {
          try {
            return JSON.parse(html.slice(start, i + 1)) as PlayerResponse;
          } catch {
            return null;
          }
        }
      }
    }
  }
  return null;
}

async function fetchWatchPageResponse(
  videoId: string
): Promise<PlayerResponse | null> {
  const res = await fetch(`https://www.youtube.com/watch?v=${videoId}`, {
    headers: {
      'user-agent': UA,
      accept: 'text/html,application/xhtml+xml,*/*;q=0.8',
      'accept-language': 'en-US,en;q=0.9',
      // Skip the consent interstitial some regions get.
      cookie: 'CONSENT=YES+1; SOCS=CAI',
    },
    redirect: 'follow',
  });
  if (!res.ok) return null;
  return playerResponseFromHtml(await res.text());
}

/**
 * The InnerTube player API with the ANDROID client. This is the primary
 * source: its caption-track URLs are served without the proof-of-origin
 * token that gates the web watch page's track URLs (those 200 with an empty
 * body), and the response carries `videoDetails` too.
 */
async function fetchInnertubeResponse(
  videoId: string
): Promise<PlayerResponse | null> {
  const res = await fetch(
    'https://www.youtube.com/youtubei/v1/player?prettyPrint=false',
    {
      method: 'POST',
      headers: {
        'content-type': 'application/json',
        'user-agent':
          'com.google.android.youtube/20.10.38 (Linux; U; Android 11) gzip',
      },
      body: JSON.stringify({
        videoId,
        context: {
          client: {
            clientName: 'ANDROID',
            clientVersion: '20.10.38',
            androidSdkVersion: 30,
            hl: 'en',
          },
        },
      }),
    }
  );
  if (!res.ok) return null;
  try {
    return (await res.json()) as PlayerResponse;
  } catch {
    return null;
  }
}

/**
 * Prefer a human-uploaded track over auto-captions, and English over other
 * languages within each tier (transcripts are primarily for search).
 */
function pickTrack(tracks: CaptionTrack[]): CaptionTrack | null {
  const scored = tracks
    .filter(t => t.baseUrl)
    .map(track => {
      const manual = track.kind !== 'asr';
      const english = /^en(-|$)/.test(track.languageCode);
      return { track, score: (manual ? 2 : 0) + (english ? 1 : 0) };
    })
    .sort((a, b) => b.score - a.score);
  return scored[0]?.track ?? null;
}

interface Json3Event {
  tStartMs?: number;
  dDurationMs?: number;
  segs?: { utf8?: string }[];
}

const XML_ENTITIES: Record<string, string> = {
  '&amp;': '&',
  '&lt;': '<',
  '&gt;': '>',
  '&quot;': '"',
  '&#39;': "'",
  '&apos;': "'",
};

function decodeEntities(value: string): string {
  return value
    .replace(/&#(\d+);/g, (_, code) => String.fromCodePoint(Number(code)))
    .replace(/&[a-z]+;|&#39;/g, m => XML_ENTITIES[m] ?? m);
}

function cleanText(value: string): string {
  return decodeEntities(value)
    .replace(/<[^>]+>/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

function parseJson3(data: { events?: Json3Event[] }): TranscriptSegment[] {
  const segments: TranscriptSegment[] = [];
  for (const event of data.events ?? []) {
    const text = (event.segs ?? [])
      .map(s => s.utf8 ?? '')
      .join('')
      .replace(/\s+/g, ' ')
      .trim();
    if (!text) continue;
    segments.push({
      start: (event.tStartMs ?? 0) / 1000,
      dur: (event.dDurationMs ?? 0) / 1000,
      text,
    });
  }
  return segments;
}

/**
 * Parse the timedtext XML shapes: srv3 `<p t="ms" d="ms">…</p>` (what the
 * ANDROID client serves regardless of the requested fmt) and the legacy
 * `<text start="s" dur="s">…</text>`.
 */
function parseTimedtextXml(xml: string): TranscriptSegment[] {
  const segments: TranscriptSegment[] = [];
  for (const m of xml.matchAll(
    /<p\b([^>]*)>([\s\S]*?)<\/p>|<text\b([^>]*)>([\s\S]*?)<\/text>/g
  )) {
    const isP = m[1] !== undefined;
    const attrs = (isP ? m[1] : m[3]) ?? '';
    const text = cleanText((isP ? m[2] : m[4]) ?? '');
    if (!text) continue;
    if (isP) {
      const t = Number(attrs.match(/\bt="([\d.]+)"/)?.[1] ?? 0);
      const d = Number(attrs.match(/\bd="([\d.]+)"/)?.[1] ?? 0);
      segments.push({ start: t / 1000, dur: d / 1000, text });
    } else {
      const start = Number(attrs.match(/\bstart="([\d.]+)"/)?.[1] ?? 0);
      const dur = Number(attrs.match(/\bdur="([\d.]+)"/)?.[1] ?? 0);
      segments.push({ start, dur, text });
    }
  }
  return segments;
}

async function fetchTrackSegments(
  baseUrl: string
): Promise<TranscriptSegment[]> {
  const url = `${baseUrl}${baseUrl.includes('?') ? '&' : '?'}fmt=json3`;
  const res = await fetch(url, { headers: { 'user-agent': UA } });
  if (!res.ok) {
    throw new Error(`Transcript track fetch failed (${res.status})`);
  }
  const body = (await res.text()).trim();
  // WEB-client track URLs are proof-of-origin gated and return an empty 200 —
  // treat that as "no transcript from this track" so the caller can try
  // another source.
  if (!body) return [];
  if (body.startsWith('<')) {
    return parseTimedtextXml(body);
  }
  try {
    return parseJson3(JSON.parse(body) as { events?: Json3Event[] });
  } catch {
    return [];
  }
}

/**
 * Fetch the transcript for a YouTube video. Throws with a user-presentable
 * message when the video has no captions or can't be read.
 */
export async function fetchYoutubeTranscript(
  url: string
): Promise<VideoTranscript> {
  const videoId = parseYoutubeVideoId(url);
  if (!videoId) {
    throw new Error('Not a YouTube video URL');
  }

  let response: PlayerResponse | null = null;
  let track: CaptionTrack | null = null;
  let segments: TranscriptSegment[] = [];
  // ANDROID InnerTube first (ungated track URLs), watch page as fallback.
  for (const source of [fetchInnertubeResponse, fetchWatchPageResponse]) {
    const candidate = await source(videoId);
    if (!candidate) continue;
    response = response
      ? { ...candidate, videoDetails: response.videoDetails ?? candidate.videoDetails }
      : candidate;
    const tracks =
      candidate.captions?.playerCaptionsTracklistRenderer?.captionTracks ??
      [];
    track = pickTrack(tracks);
    if (!track) continue;
    segments = await fetchTrackSegments(track.baseUrl);
    if (segments.length > 0) break;
  }
  if (!response) {
    throw new Error('Could not read the video page');
  }
  if (!track) {
    const reason = response.playabilityStatus?.reason;
    throw new Error(
      reason
        ? `Video has no captions (${reason})`
        : 'Video has no captions/transcript'
    );
  }
  if (segments.length === 0) {
    throw new Error('Transcript track was empty');
  }

  const details = response.videoDetails;
  const lengthSeconds = Number(details?.lengthSeconds);
  return {
    videoId,
    url: `https://www.youtube.com/watch?v=${videoId}`,
    title: details?.title ?? 'YouTube video',
    channel: details?.author ?? '',
    durationSeconds: Number.isFinite(lengthSeconds)
      ? lengthSeconds
      : undefined,
    language: track.languageCode,
    autoGenerated: track.kind === 'asr',
    segments,
    text: segments.map(s => s.text).join(' '),
  };
}
